root = "."
tmp_dir = "tmp"

[build]
  bin = "/bin/true"
  cmd = "GOOS=js GOARCH=wasm go build -o web/main.wasm ./impl/web"
  delay = 1000
  exclude_dir = ["test", ".dev", "res", "bin", "misc", "stories", "web"]
  kill_delay = "0s"
  log = "build-errors.log"

[misc]
  clean_on_exit = true

[screen]
  clear_on_rebuild = true
  keep_scroll = true