root = "."
tmp_dir = "tmp"

[build]
  args_bin = ["stories/scratch.z3"]
  bin = "./tmp/gozm"
  cmd = "go build -o ./tmp/gozm cmd/cli/main.go"
  delay = 1000
  exclude_dir = ["test", ".dev", "res", "bin", "misc", "stories"]
  kill_delay = "0s"
  log = "build-errors.log"
  
[misc]
  clean_on_exit = true

[screen]
  clear_on_rebuild = true
  keep_scroll = true